### ISSUE TITLE
Working Example

### ISSUE THREAD

**Issue by ErmalKristo** [qaxi/ansible-ciscosmb#4]
Hello Petr

i want to congratulate you for creating this module.
I'm trying to use it in a playbook but till now without success.

This is the configuration i am using.
hosts

> [cisco-smb]
> CISCO-SF300-211 ansible_host=192.168.10.211
> 
> 
> [cisco-smb:vars]
> become=no
> ansible_connection=network_cli
> ansible_network_os=ios
> ansible_user=cisco
> ansible_password=XXXXXXX
> ansible_become_pass=XXXXXXX

This is the playbook

> ---
> - hosts: cisco-smb
>   vars_files:
>   - ./vault/secrets.yaml    
>   tasks: 
>     - name: run show running-config on ciscosmb switches
>       qaxi.ciscosmb.ciscosmb_facts:
>         gather_subset:
>         - config
>       register: running_config
>     - name: copy Running config to backup folder
>       copy:
>         content: "{{ running_config.stdout[0] }}"
>         dest: "./backup/{{ inventory_hostname }}.txt"

This is the output of the playbook exec:

> fatal: [CISCO-SF300-211]: FAILED! => {
>     "ansible_facts": {},
>     "changed": false,
>     "failed_modules": {
>         "ios_facts": {
>             "ansible_facts": {
>                 "discovered_interpreter_python": "/usr/bin/python3"
>             },
>             "exception": "  File \"/tmp/ansible_ios_facts_payload_yxvvh2vi/ansible_ios_facts_payload.zip/ansible/module_utils/network/common/network.py\", line 229, in get_capabilities\n    capabilities = Connection(module._socket_path).get_capabilities()\n  File \"/tmp/ansible_ios_facts_payload_yxvvh2vi/ansible_ios_facts_payload.zip/ansible/module_utils/connection.py\", line 185, in __rpc__\n    raise ConnectionError(to_text(msg, errors='surrogate_then_replace'), code=code)\n",
>             "failed": true,
>             "invocation": {
>                 "module_args": {
>                     "auth_pass": null,
>                     "authorize": null,
>                     "gather_network_resources": null,
>                     "gather_subset": [
>                         "all"
>                     ],
>                     "host": null,
>                     "password": null,
>                     "port": null,
>                     "provider": null,
>                     "ssh_keyfile": null,
>                     "timeout": null,
>                     "username": null
>                 }
>             },
>             "msg": "Failed to authenticate: Bad authentication type; allowed types: ['']"
>         }
>     },
>     "msg": "The following modules failed to execute: ios_facts\n"
> 

Plase can you put a full working example in the docs.

Regards

**Comment by qaxi** [comment]
Hi,
good point.

Will write it ASAP.

**Comment by qaxi** [comment]
But for now, it seems you hit an error in implementation or misunderstunding.

1. no IOS on Cisco SMB switches ... the software has no name, so I named it ciscosmb
2. use `ansible_network_os=qaxi.ciscosmb.ciscosmb` 
3. getting config is now unpredictable ...

**Comment by qaxi** [comment]
Example added by commit https://github.com/qaxi/ansible-ciscosmb/commit/87e8ceeea4ab3cb17e0a8b235eabb5b247adb636
